### ISSUE TITLE
Open Development Method badge?

### ISSUE THREAD

**Issue by brylie** [OpenDevelopmentMethod/discussion#4]
Is there an Open Development Method badge we can add to our README? Here are a few examples, created on [Shields.io](http://shields.io/):

![Open Development Method: Yes](https://img.shields.io/badge/Open%20Development%20Method-Yes-green.svg)

![Open Development Method: True](https://img.shields.io/badge/Open%20Development%20Method-True-green.svg)

![Open Development Method: True](https://img.shields.io/badge/Development%20Method-Open-blue.svg)

**Comment by ahmadnassri** [comment]
love it :+1: 

let the community vote on what makes more sense.

I'm in favor of third option, (with green background)

**Comment by seanballais** [comment]
That's great! The third option is plainly brilliant! :+1: Go for it.

**Comment by brylie** [comment]
I like the third option as well. Since we have three votes for the third option, should we add it as a recommendation to the README?

**Comment by seanballais** [comment]
@brylie I'd say yes.

**Comment by ahmadnassri** [comment]
@brylie a PR would be great :)

**Comment by mcmahonjohn** [comment]
Since this has been added to the README, should this be closed?
