### ISSUE TITLE
Interested in translation to spanish of opendevelopmentmethod.org

### ISSUE THREAD

**Issue by adrianpelaez** [OpenDevelopmentMethod/discussion#8]
Hello,

I'm Adrian, from <a href="http://autentia.com/">Autentia<a>, a Software Company from Madrid, Spain. I'd like to offer you a Spanish translation for your site opendevelopmentmethod.org, Beyond Agile article.

Spanish Community would thank this translation. Please tell me if you are interested.

Regards,

Adrian.

**Comment by ahmadnassri** [comment]
@adrianpelaez that would great! please do it as a Pull Request to this repository, and I can work on providing an easy navigation for different translations. :+1:
